[package]
name = "rust_roguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
derive_more = "0.99.17"
dyn-clone = "1.0.9"
enum-as-inner = "0.6.0"
euclid = "0.22.7"
line_drawing = "1.0"
ntest = "0.9.0"
num = "0.4"
ordered-float = "3.3.0"
rand = "0.8.4"
rgb = "0.8.34"
strum = "0.25.0"
strum_macros = "0.25.1"
termion = "2.0.1"
priority-queue = "1.2.3"
itertools = "0.11.0"
shrinkwraprs = "0.3.0"
getset = "0.1.2"
ambassador = "0.3.5"
color-backtrace = { version = "0.6" }

[dev-dependencies]
pretty_assertions = "1.3.0"
