[package]
name = "rust_roguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
derive_more = "0.99.17"
device_query = "1.1.1"
dyn-clone = "1.0.9"
enum-as-inner = "0.5.1"
euclid = "0.22.7"
line_drawing = "1.0"
ntest = "0.9.0"
num = "0.4"
ordered-float = "3.3.0"
rand = "0.8.4"
rgb = "0.8.34"
strum = "0.24"
strum_macros = "0.24"
termion = "2.0.1"
priority-queue = "1.2.3"
itertools = "0.10.5"
unordered-pair = "0.2.4"

[dev-dependencies]
pretty_assertions = "1.3.0"