[package]
name = "realtime_terminal_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
line_drawing = "1.0"
num = "0.4"
assert2 = "0.3.6"
geo = "0.18.0"
device_query = "0.2.8"
rand = "0.8.4"
approx = "0.5.1"
enum-as-inner = "0.3.3"
ntest = "0.7.3"
ordered-float = "2.10.0"
derive_more = "0.99.17"
strum = "0.24.0"
strum_macros = "0.24"