[package]
name = "angles"
version = "0.0.0"
edition.workspace = true

[dependencies]
angular-units.workspace = true
automod.workspace = true
ntest.workspace = true
derive_more.workspace = true
# misc_utilities.workspace = true
# num.workspace = true

