[build]
rustflags = [
  '-Cinstrument-coverage',
  '-Cforce-frame-pointers=yes',
  '-Zinstrument-mcount',
  '-Cpasses=ee-instrument<post-inline>'
]

[env]
LLVM_PROFILE_FILE = "coverage/%p-%m.profraw"
